### ISSUE TITLE
Historical events detail page modifications

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass-frontend#28]
Since the information on this page is plain text, the page looks a bit ugly like this.
We propose to revise the design, and maybe display it in a similar way as here:
http://policy.atosresearch.eu/viewer.html (text under the visualisation)

~~Also, the Create Visualisation button should be removed.~~

~~Instead, it should list the Visualisations where this historical event is annotated.~~

**Comment by FabiApfelkern** [comment]
@almey Can we close this?
