### ISSUE TITLE
Possibility to disable Piwik integration

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass-frontend#437]
There seems not to be a way to disable the Piwik integration, e.g. for local development. Any missing config value leads to a broken page.

**Comment by slomo** [comment]
It should be disabled in [app.js](https://github.com/policycompass/policycompass-frontend/blob/master/app/app.js#L72) if PIWIK_TRACKER_URL is not set.

**Comment by FabiApfelkern** [comment]
"Any missing config value leads to a broken page." I tried this.

**Comment by cbotsikas** [comment]
Indeed.. I've fixed the issue.

The error was that $log wasn't injected. I've changed that to native console ([you can't use $log within config](http://stackoverflow.com/a/25984664)) and also added a check if both mandatory configurations exist.
