### ISSUE TITLE
Visualisation: legend checkbox should not be displayed under the metric tab

### ISSUE THREAD

**Issue by lfarid** [policycompass/policycompass-frontend#66]
the legend checkboxes would be better to be part of the visualisation canvas

**Comment by mmilaprat** [comment]
can you explain your suggestion a bit more?

**Comment by lfarid** [comment]
In edit visualisation mode the checkboxes : show legend, show lines , show areas, etc. are below the metric tab. So if you click on the other tabs like  historical event, for instance, these check boxes are not available anymore as they are hidden behind the selected tab. The checkboxes should be part of the visualisation/graph itself not the metrics tab.

**Comment by mmilaprat** [comment]
done.
The checkboxes appears out of the "Metrics" tab.
