### ISSUE TITLE
The chart should remember the colors of individual metrics

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass-frontend#87]
If I visualise a dataset with data for two countries like "Drug law offences In Germany and Spain, 1996–2009 - April 15, 2015" then the lines are dark blue and light blue. If I add an additional metric to visualisation like "Deaths from drug dependance and toxicomania in Spain -- April 14, 2015" then the last one becomes dark blue. It is a bug. The first metric should keep its colors after adding another one.

**Comment by mmilaprat** [comment]
A new functionality that enable users to select the color per dataset is under construction
