### ISSUE TITLE
It should be possible to deactivate  one or several datasets visualisations

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass-frontend#89]
It should be possible to deactivate  one or several datasets visualisations without deleting them from the visualisation. For example, if I have a visualisation of "Drug law offences In Germany and Spain, 1996–2009 -- April 15, 2015" with separation on countries, I should be able to deactivate one of them by clicking on their legend.

**Comment by mmilaprat** [comment]
please check: https://alpha.policycompass.eu/app/#/visualizations/2 

if you click over the legends you can hide/show lines.
