### ISSUE TITLE
create directive to use Chardin.js

### ISSUE THREAD

**Issue by lfarid** [policycompass/policycompass-frontend#93]
as written in D2.2 we want to use Chardin.js to create helpful text to aid users with using the tools. a directive is needed to be included in all affected frontends.

**Comment by mmilaprat** [comment]
The idea is to create a new directive (helpbutton) into the common directives folder.

This new directive will display a link with a text like "View help". 

It must be added in each page that we wish to add help.

<div class="helpbutton"></div>

If users click the link "View help", Cardin.js will show the "help" text that follows this rules:

data-intro="Visualisation graph" data-position="top"

an example:

<div data-intro="Help text" data-position="top"></div>


data-position can be: top, bottom, left, right
